### ISSUE TITLE
merge into athena-query-federation?

### ISSUE THREAD

**Issue by avirtuos** [dacort/athena-sqlite#1]
Hey @dacort,

Curious if you'd be open to us merging this into the athena-query-federation as a connector.

**Comment by dacort** [comment]
Hey @avirtuos! 

Yes! Totally open to that - one question I have is around maintenance/updates. This project is definitely still in it's infancy and I'll likely be making occasional updates, but looks like things are getting merged into that repo pretty regularly. As long as that's the expectation and y'all don't mind a Python implementation of this, then 👍 .

**Comment by avirtuos** [comment]
I'm open to having a 'beta' flag for connectors that are still undergoing rapid changes. I think having this in the athena-query-federation repo will improve discoverability. I'm also very excited you got a python version working. Can you give me more info about how you handled the serialization in Python in a way that was compatible with our current serialization? I have plans to move us off ObjectMapper so we can have a more easily documented and controlled spec for the json.

**Comment by dacort** [comment]
I agree re: discoverability. 

re: the serialization, it's not pretty. I ended up reverse engineering responses coming back from one of the example connectors along with poking at the connector source and experimenting with pyarrow locally to figure out each response type.

You can see an example of the end result [here](https://github.com/dacort/athena-sqlite/blob/eff71802b31c4fc0eb708e7c9930dc94d7533222/lambda-function/s3qlite.py#L87-L94). The main weird thing that came up was that schema serialization on macOS is different than on Linux, hence the funky `.slice(4)` to chop off the first few bytes on Linux/Lambda. 😠 

Let me know what next steps should be!

**Comment by kparwal** [comment]
Hey, sorry to raise this from the dead, but we've got some renewed interest in this connector getting merged into our main repository. Are you still working on this?

**Comment by dacort** [comment]
Chatted offline about this - For now, given that main repo is all Java and this implementation is Python, going to hold off on trying to merge this in. 

I'm going to close this issue for now, but always happy to consider contributing it back as an official connector. :)

I also plan to refactor this on top of the [Python SDK](https://github.com/dacort/athena-federation-python-sdk) I wrote.
